version: '3.8'
services:
  auditoria.api:
    image: auditoria.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: '8080'
      OTEL_SERVICE_NAME: 'auditoria'
      APPLICATIONINSIGHTS_CONNECTION_STRING: 'InstrumentationKey=00000000-0000-0000-0000-000000000000;'
      Serilog__MinimumLevel__Default: 'Information'
      Serilog__MinimumLevel__Override__Host: 'Information'
      Serilog__MinimumLevel__Override__Microsoft: 'Information'
      Serilog__MinimumLevel__Override__Microsoft.AspNetCore: 'Information'
      Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore: 'Information'
      Serilog__MinimumLevel__Override__Microsoft.Hosting.Lifetime: 'Information'
      Serilog__MinimumLevel__Override__System: 'Information'
      Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore.Database.Command: 'Information'
      ConnectionStrings__Mongo: mongodb://mongodb:27017/Auditoria
    networks:
      - env_local

  mongodb:
    container_name: auditoria.mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - env_local

  rabbitmq:
    container_name: auditoria.rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 5672
      - 15672
    networks:
      - env_local

networks:
  env_local: