namespace RabbitMqPublisher;

public static class DadosFake
{
    public static List<string> RecuperarDadosFake() =>
    [
        "{\"idoriginal\":1,\"idtenant\":101,\"idunidade\":1,\"idusuario\":23,\"entidadeauditada\":\"Pessoa\",\"tipo\":\"Alteracao\",\"dados\":\"{\\\"Tipo\\\":\\\"Fisica\\\",\\\"Nome\\\":\\\"Nome Fake 1\\\",\\\"TemResponsavel\\\":false,\\\"CodigoClienteResponsavel\\\":null,\\\"Origem\\\":\\\"Site\\\",\\\"CodigoOrigem\\\":1,\\\"Observacao\\\":\\\"Gerado automaticamente\\\",\\\"NotificarWhatsApp\\\":true,\\\"DddFone\\\":\\\"11\\\",\\\"Sexo\\\":\\\"Masculino\\\",\\\"DataNascimento\\\":\\\"1990-01-01\\\",\\\"Fone\\\":\\\"900000001\\\",\\\"Email\\\":\\\"email1@exemplo.com\\\",\\\"Cpf\\\":\\\"00000000001\\\",\\\"Rg\\\":\\\"0000001\\\",\\\"CodigoObjetivo\\\":1,\\\"Cep\\\":\\\"00000000\\\",\\\"Endereco\\\":\\\"Rua 1\\\",\\\"NumEndereco\\\":\\\"1\\\",\\\"CompleEndereco\\\":\\\"Apto 1\\\",\\\"Bairro\\\":\\\"Centro\\\",\\\"CodigoCidade\\\":1234567,\\\"CodigoUsuarioConsultor\\\":23,\\\"CodigoTenant\\\":101,\\\"Id\\\":1,\\\"DataCriacao\\\":\\\"2024-01-01T00:00:00\\\",\\\"DataAlteracao\\\":\\\"2024-01-02T00:00:00\\\",\\\"CodigoUsuarioCriacao\\\":23,\\\"CodigoUsuarioAlteracao\\\":23}\"}",
        "{\"idoriginal\":12,\"idtenant\":102,\"idunidade\":1,\"idusuario\":78,\"entidadeauditada\":\"Item\",\"tipo\":\"Remocao\"}",
        "{\"idoriginal\":3,\"idtenant\":103,\"idunidade\":1,\"idusuario\":45,\"entidadeauditada\":\"Pessoa\",\"tipo\":\"Insercao\",\"dados\":\"{\\\"Tipo\\\":\\\"Juridica\\\",\\\"Nome\\\":\\\"Nome Fake 3\\\",\\\"TemResponsavel\\\":false,\\\"CodigoClienteResponsavel\\\":null,\\\"Origem\\\":\\\"Site\\\",\\\"CodigoOrigem\\\":1,\\\"Observacao\\\":\\\"Gerado automaticamente\\\",\\\"NotificarWhatsApp\\\":true,\\\"DddFone\\\":\\\"11\\\",\\\"Sexo\\\":\\\"Feminino\\\",\\\"DataNascimento\\\":\\\"1990-01-01\\\",\\\"Fone\\\":\\\"900000003\\\",\\\"Email\\\":\\\"email3@exemplo.com\\\",\\\"Cpf\\\":\\\"00000000003\\\",\\\"Rg\\\":\\\"0000003\\\",\\\"CodigoObjetivo\\\":1,\\\"Cep\\\":\\\"00000000\\\",\\\"Endereco\\\":\\\"Rua 3\\\",\\\"NumEndereco\\\":\\\"3\\\",\\\"CompleEndereco\\\":\\\"Apto 3\\\",\\\"Bairro\\\":\\\"Centro\\\",\\\"CodigoCidade\\\":1234567,\\\"CodigoUsuarioConsultor\\\":45,\\\"CodigoTenant\\\":103,\\\"Id\\\":3,\\\"DataCriacao\\\":\\\"2024-01-01T00:00:00\\\",\\\"DataAlteracao\\\":\\\"2024-01-02T00:00:00\\\",\\\"CodigoUsuarioCriacao\\\":45,\\\"CodigoUsuarioAlteracao\\\":45}\"}",
        "{\"idoriginal\":4,\"idtenant\":104,\"idunidade\":1,\"idusuario\":11,\"entidadeauditada\":\"Item\",\"tipo\":\"Insercao\",\"dados\":\"{\\\"Identificacao\\\":\\\"ITEM004\\\",\\\"Descricao\\\":\\\"Item de exemplo 4\\\",\\\"Tipo\\\":\\\"Produto\\\",\\\"Preco\\\":398.51,\\\"Observacao\\\":\\\"Item gerado automaticamente\\\",\\\"Id\\\":4,\\\"DataCriacao\\\":\\\"2024-01-01T00:00:00\\\",\\\"DataAlteracao\\\":\\\"2024-01-02T00:00:00\\\",\\\"CodigoUsuarioCriacao\\\":11,\\\"CodigoUsuarioAlteracao\\\":11,\\\"CodigoTenant\\\":104}\"}",
        "{\"idoriginal\":19,\"idtenant\":105,\"idunidade\":1,\"idusuario\":37,\"entidadeauditada\":\"Pessoa\",\"tipo\":\"Remocao\"}",
        "{\"idoriginal\":6,\"idtenant\":106,\"idunidade\":1,\"idusuario\":64,\"entidadeauditada\":\"Item\",\"tipo\":\"Alteracao\",\"dados\":\"{\\\"Identificacao\\\":\\\"ITEM006\\\",\\\"Descricao\\\":\\\"Item de exemplo 6\\\",\\\"Tipo\\\":\\\"Produto\\\",\\\"Preco\\\":103.33,\\\"Observacao\\\":\\\"Item gerado automaticamente\\\",\\\"Id\\\":6,\\\"DataCriacao\\\":\\\"2024-01-01T00:00:00\\\",\\\"DataAlteracao\\\":\\\"2024-01-02T00:00:00\\\",\\\"CodigoUsuarioCriacao\\\":64,\\\"CodigoUsuarioAlteracao\\\":64,\\\"CodigoTenant\\\":106}\"}",
        "{\"idoriginal\":7,\"idtenant\":107,\"idunidade\":1,\"idusuario\":19,\"entidadeauditada\":\"Pessoa\",\"tipo\":\"Insercao\",\"dados\":\"{\\\"Tipo\\\":\\\"Juridica\\\",\\\"Nome\\\":\\\"Nome Fake 7\\\",\\\"TemResponsavel\\\":false,\\\"CodigoClienteResponsavel\\\":null,\\\"Origem\\\":\\\"Site\\\",\\\"CodigoOrigem\\\":1,\\\"Observacao\\\":\\\"Gerado automaticamente\\\",\\\"NotificarWhatsApp\\\":true,\\\"DddFone\\\":\\\"11\\\",\\\"Sexo\\\":\\\"Feminino\\\",\\\"DataNascimento\\\":\\\"1990-01-01\\\",\\\"Fone\\\":\\\"900000007\\\",\\\"Email\\\":\\\"email7@exemplo.com\\\",\\\"Cpf\\\":\\\"00000000007\\\",\\\"Rg\\\":\\\"0000007\\\",\\\"CodigoObjetivo\\\":1,\\\"Cep\\\":\\\"00000000\\\",\\\"Endereco\\\":\\\"Rua 7\\\",\\\"NumEndereco\\\":\\\"7\\\",\\\"CompleEndereco\\\":\\\"Apto 7\\\",\\\"Bairro\\\":\\\"Centro\\\",\\\"CodigoCidade\\\":1234567,\\\"CodigoUsuarioConsultor\\\":19,\\\"CodigoTenant\\\":107,\\\"Id\\\":7,\\\"DataCriacao\\\":\\\"2024-01-01T00:00:00\\\",\\\"DataAlteracao\\\":\\\"2024-01-02T00:00:00\\\",\\\"CodigoUsuarioCriacao\\\":19,\\\"CodigoUsuarioAlteracao\\\":19}\"}",
        "{\"idoriginal\":8,\"idtenant\":108,\"idunidade\":1,\"idusuario\":22,\"entidadeauditada\":\"Item\",\"tipo\":\"Insercao\",\"dados\":\"{\\\"Identificacao\\\":\\\"ITEM008\\\",\\\"Descricao\\\":\\\"Item de exemplo 8\\\",\\\"Tipo\\\":\\\"Produto\\\",\\\"Preco\\\":77.92,\\\"Observacao\\\":\\\"Item gerado automaticamente\\\",\\\"Id\\\":8,\\\"DataCriacao\\\":\\\"2024-01-01T00:00:00\\\",\\\"DataAlteracao\\\":\\\"2024-01-02T00:00:00\\\",\\\"CodigoUsuarioCriacao\\\":22,\\\"CodigoUsuarioAlteracao\\\":22,\\\"CodigoTenant\\\":108}\"}",
        "{\"idoriginal\":9,\"idtenant\":109,\"idunidade\":1,\"idusuario\":51,\"entidadeauditada\":\"Pessoa\",\"tipo\":\"Alteracao\",\"dados\":\"{\\\"Tipo\\\":\\\"Juridica\\\",\\\"Nome\\\":\\\"Nome Fake 9\\\",\\\"TemResponsavel\\\":false,\\\"CodigoClienteResponsavel\\\":null,\\\"Origem\\\":\\\"Site\\\",\\\"CodigoOrigem\\\":1,\\\"Observacao\\\":\\\"Gerado automaticamente\\\",\\\"NotificarWhatsApp\\\":true,\\\"DddFone\\\":\\\"11\\\",\\\"Sexo\\\":\\\"Feminino\\\",\\\"DataNascimento\\\":\\\"1990-01-01\\\",\\\"Fone\\\":\\\"900000009\\\",\\\"Email\\\":\\\"email9@exemplo.com\\\",\\\"Cpf\\\":\\\"00000000009\\\",\\\"Rg\\\":\\\"0000009\\\",\\\"CodigoObjetivo\\\":1,\\\"Cep\\\":\\\"00000000\\\",\\\"Endereco\\\":\\\"Rua 9\\\",\\\"NumEndereco\\\":\\\"9\\\",\\\"CompleEndereco\\\":\\\"Apto 9\\\",\\\"Bairro\\\":\\\"Centro\\\",\\\"CodigoCidade\\\":1234567,\\\"CodigoUsuarioConsultor\\\":51,\\\"CodigoTenant\\\":109,\\\"Id\\\":9,\\\"DataCriacao\\\":\\\"2024-01-01T00:00:00\\\",\\\"DataAlteracao\\\":\\\"2024-01-02T00:00:00\\\",\\\"CodigoUsuarioCriacao\\\":51,\\\"CodigoUsuarioAlteracao\\\":51}\"}",
        "{\"idoriginal\":55,\"idtenant\":110,\"idunidade\":1,\"idusuario\":88,\"entidadeauditada\":\"Item\",\"tipo\":\"Remocao\"}"
    ];
}