# server:
#   extraFlags:
#     - enable-feature=otlp-write-receiver

extraScrapeConfigs: |
  - job_name: 'prometheus-otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: [ simplest-collector.default.svc:8889 ]